apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k2xkzdknl-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/k2xkzdknl-nodejs-gitops