apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k2xkzdknl-nodejs-gitops
  description: This is GitOps manifest for k2xkzdknl-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=k2xkzdknl-nodejs
    backstage.io/kubernetes-id: k2xkzdknl-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: k2xkzdknl-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k2xkzdknl-nodejs
